### ISSUE TITLE
No support for Advanced configuration for hosted websites

### ISSUE THREAD

**Issue by dguihal** [banyansecurity/terraform-provider-banyan#107]
Hi banyan people

looks like those advanced features aren't supported by provider https://registry.terraform.io/providers/banyansecurity/banyan/latest/docs/resources/service_web

https://docs.banyansecurity.io/docs/feature-guides/hosted-websites/notes/#customizing-the-bnn_trust-cookie

**Comment by tdesikan** [comment]
Exemptions are not supported either:
https://github.com/banyansecurity/terraform-provider-banyan/blob/main/banyan/resource_service_web.go#L299
