### ISSUE TITLE
v0.6.3 - connector install fails w orgs that have multiple access tiers

### ISSUE THREAD

**Issue by tdesikan** [banyansecurity/terraform-provider-banyan#46]
the code in https://github.com/banyansecurity/terraform-provider-banyan/blob/beta/banyan/resource_connector.go#L68 only works if the org has 1 access-tier with the name `access-tier`.

this fails in orgs with a true global edge with multiple access tiers.

instead, make it `AccessTiers: []string{"*"}` so it works generally.

**Comment by TheMattSchiller** [comment]
Addressed in 0.9.0
