### ISSUE TITLE
v1.0.x - banyan_policy_tunnel does not display multiple access groups in console

### ISSUE THREAD

**Issue by pjain-taylor** [banyansecurity/terraform-provider-banyan#94]
### Error Reported
The following configuration for `banyan_policy_tunnel` is valid in v1.0.x of the Terraform provider:

```terraform
resource "banyan_policy_tunnel" "policy" {
  name        = var.name
  description = var.description
  access {
    roles       = [for role in var.access_roles : role.name]
    trust_level = var.access_trust_level
    l4_access {
      dynamic "allow" {
        for_each = var.l4_access_allow
        content {
          cidrs     = allow.value.cidrs
          protocols = allow.value.protocols
          ports     = allow.value.ports
        }
      }
    }
  }
}
```

However, deploying this configuration only displays the first of the displayed access groups. I've confirmed that I am still able to access the tunneled resources without issue, so this is either a console bug, or an API bug.

### Provider Affected
`provider[registry.terraform.io/banyansecurity/banyan] 1.0.0`

**Comment by TheMattSchiller** [comment]
this appears to be a bug and we are looking into it

**Comment by pjain-taylor** [comment]
The ultimate resolution for this on my end was changing the block accordingly:

```terraform
resource "banyan_policy_tunnel" "policy" {
  name        = var.name
  description = var.description
  dynamic "access" {
    for_each = var.l4_access_allow
    content {
      roles       = [for role in var.access_roles : role.name]
      trust_level = var.access_trust_level
      l4_access {
        allow {
          cidrs     = access.value.cidrs
          protocols = access.value.protocols
          ports     = access.value.ports
        }
      }
    }
  }
}
```
With this in place, I was able to see the access groups in the console; we may want to put some validation in place to prevent dynamic `allow` blocks for `l4_access`.

**Comment by TheMattSchiller** [comment]
the next release will make it so that there can only be one allow and one deny block
