### ISSUE TITLE
v1.0.x: banyan_service_tunnel only displays 1 access tier, even if multiple defined

### ISSUE THREAD

**Issue by pjain-taylor** [banyansecurity/terraform-provider-banyan#95]
### Error Reported
The following configuration for `banyan_service_tunnel` is valid in v1.0.x of the Terraform provider:

```terraform
resource "banyan_service_tunnel" "service" {
  access_tiers = var.access_tiers
  description  = var.description
  name         = var.name
  policy       = var.policy.id
}
```

However, deploying this configuration only displays the first of the defined access tiers. I've confirmed that I am still able to access the tunneled resources without issue, so this is either a console bug, or an API bug.

### Provider Affected
`provider[registry.terraform.io/banyansecurity/banyan] 1.0.0`

**Comment by TheMattSchiller** [comment]
you are able to access resources behind either access tier when you have two configured, but only one shows in the UI?

**Comment by pjain-taylor** [comment]
Only one shows in the UI, but when I look at the tunnel details in the app, it shows all CIDR ranges associated with the access tiers, which should only happen if the configured access tiers are defined.

**Comment by pjain-taylor** [comment]
This issue can be closed, as the new Banyan UI shows all access tiers assigned to the tunnel.
